/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;

/**
 *
 * @author curro
 */
public class NuevoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form NuevoUsuario
     */
    public NuevoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        spinnerSaldo = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 20, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre de usuario:");
        jPanel1.add(jLabel1);
        jPanel1.add(lblUser);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3);
        jPanel1.add(pass1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4);
        jPanel1.add(pass2);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Saldo:");
        jPanel1.add(jLabel2);

        spinnerSaldo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        jPanel1.add(spinnerSaldo);

        add(jPanel1);

        btnCrear.setText("Crear");
        jPanel2.add(btnCrear);

        btnCerrar.setText("Cerrar");
        jPanel2.add(btnCerrar);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    public String getUser(){
        return lblUser.getText();
    }
    
    public String getPass(){
        return String.valueOf(pass1.getPassword());
    }
    public double getSaldo(){
        return (double) spinnerSaldo.getValue();
    }
    
    public boolean passIguales(){
        return (String.valueOf(pass1.getPassword()).equals(String.valueOf(pass2.getPassword()))) ? true : false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lblUser;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JSpinner spinnerSaldo;
    // End of variables declaration//GEN-END:variables

    public void addControlador(ActionListener c){
        btnCerrar.addActionListener(c);
        btnCrear.addActionListener(c);
        btnCerrar.setActionCommand("CERRAR");
        btnCrear.setActionCommand("CREAR");
    }

}
