/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import java.util.List;
import modelo.CuentaException;

/**
 *
 * @author curro
 */
public class NuevoMovimiento extends javax.swing.JPanel {

    /**
     * Creates new form AddMovimiento
     */
    public NuevoMovimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboConcepto = new javax.swing.JComboBox();
        checkNuevoConcepto = new javax.swing.JCheckBox();
        labelConcepto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        importe = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnExtraer = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Concepto");
        jPanel1.add(jLabel1);

        comboConcepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboConcepto);

        checkNuevoConcepto.setText("Nuevo concepto");
        checkNuevoConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkNuevoConceptoMouseClicked(evt);
            }
        });
        jPanel1.add(checkNuevoConcepto);

        labelConcepto.setEnabled(false);
        jPanel1.add(labelConcepto);

        jLabel2.setText("Importe");
        jPanel1.add(jLabel2);

        importe.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        jPanel1.add(importe);

        add(jPanel1);

        btnIngresar.setText("Ingresar");
        jPanel2.add(btnIngresar);

        btnExtraer.setText("Extraer");
        jPanel2.add(btnExtraer);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void checkNuevoConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNuevoConceptoMouseClicked
        if (checkNuevoConcepto.isSelected()) {
            labelConcepto.setEnabled(true);
        } else {
            labelConcepto.setEnabled(false);
        }
    }//GEN-LAST:event_checkNuevoConceptoMouseClicked

    public void addManejador(ActionListener al) {
        btnExtraer.addActionListener(al);
        btnIngresar.addActionListener(al);
        btnExtraer.setActionCommand("EXTRAER");
        btnIngresar.setActionCommand("INGRESAR");
    }

    public void setConceptos(List<String> conceptos) {
        comboConcepto.removeAllItems();
        for (String concepto : conceptos) {
            comboConcepto.addItem(concepto);
        }
    }

    public String getConcepto() {
        String concepto = null; 
        if (checkNuevoConcepto.isSelected()) {
            concepto = labelConcepto.getText();
                            
        } else {
            if (comboConcepto.getItemCount() > 0)
                concepto = comboConcepto.getSelectedItem().toString();
        }
        return concepto;
    }

    public double getImporte() throws CuentaException {
        System.out.println(importe.getValue().toString());
        if ((double) importe.getValue() == 0) {
            throw new CuentaException("Importe erróneo");
        }
        return (double) importe.getValue();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExtraer;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JCheckBox checkNuevoConcepto;
    private javax.swing.JComboBox comboConcepto;
    private javax.swing.JSpinner importe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField labelConcepto;
    // End of variables declaration//GEN-END:variables
}
